language: node_js
node_js:
- '0.10'
env:
  global:
    - secure: eTTvdO6T70nLwdhIFXuo58nWavBL1896CeGrUtj697BuS7zCirJZhS8p/BG7v53nOBL1Wa8dPE/vTdowWuCp5XqToOH7FeIMEETIEdhLSLcYE1u/FYC1XssOpEVFkfscZ0yW6tmYmoc0pxn30L98LdPO4xUM4w8h1xq7QwDZzso=
    - secure: jD8xcL4DJDrgUag6nXNQf1VZJ+ym89rnGHT5Z++GV/8DHVFG+gSaFduE1g8FBa7TwzDwLIq9YU52JsuUFb+j8g34BJ72LYdv2WZzKtpmGbGIAmqZvP/FqQstSaoJkOW0hu1K7UbU5cjQ9ZZq6+JpLuLQVtMHbaAuSkFUSbJW0i4=
notifications:
  email: false
before_script: npm install -g karma-cli
